### ISSUE TITLE
Remove previous dist.lua

### ISSUE THREAD

**Issue by Stefanuk12** [Belkworks/tape#12]
If you use tape twice, it will simply append the output. This may cause some issues. Add an option to automatically delete the output file before writing (or overwrite)

**Comment by safazi** [comment]
Possibly fixed by https://github.com/Belkworks/tape/commit/f2215eca900bfebb8bcd0555656fe197f44fcecb
Please update your tape installation and report back

**Comment by Stefanuk12** [comment]
This has not fixed it, unfortunately. To test, I cloned the test folder and ran `tape .` twice.

**Comment by safazi** [comment]
Running `tape .` will also bundle the bundled output. Please run `tape src` or whatever.
